[template]
cargo_generate_version = ">=0.9.0"

# NOTE(canardleteer): Any way to specify a default?
sub_templates = ["tonic-buf-template"]

# TODO(canardleteer):
# - generated workflows
# - rust versions w/ workflow support
# - protobuf location instead of in-repo
# - ... many more in the README