[package]
name = "{{project-name}}-bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
tonic.workspace = true
prost.workspace = true
prost-types.workspace = true
tracing.workspace = true

[build-dependencies]
tonic-build.workspace = true
walkdir = "2.5.0"