[package]
name = "{{project-name}}-service"
version = "0.1.0"
edition = "2021"

[dependencies]
{{project-name}}-bindings = { version = "0.1.0", path = "../{{project-name}}-bindings" }

tokio.workspace = true
tonic.workspace = true
prost.workspace = true
tracing.workspace = true