# NOTE(canardleteer): Thes values, in general, need to be the same as in
#                     `.github/workflows`. Alternatively, we could let them
#                     drift apart, or we could fully integrate with GitHub and
#                     make them environment variables, but I'm not ready to do
#                     that yet.
[values]
rust_channel = "1.78.0"
rust_profile = "default"
